### ISSUE TITLE
4.2 Hardware Interfaces

### ISSUE THREAD

**Issue by cliu54** [marcusvan/seng321_1#6]

**Comment by yufei0512** [comment]
Rationale: we want to increase the accuracy of whale sighting's location by implementing the automatic GPS function, if users want to use this function, they to allow the system to access their mobiles' GPS position system
Test Scenario: 1. make a report 2. click on the location box 3. allow the system to connect the mobile's GPS position system 4. see if the location box is automatically filled 5. check the accuracy 6. disable the automatic GPS function 5. fill the location box by hand.

**Comment by yufei0512** [comment]
REQ-3: camera
Rationale: people may want to make a report on their phone, and we can increase the user-friendly by allowing people to upload photos to the report or directly taking photos when completing the report. if people want to have this function, they should allow the system to have the permission of their camera and photo gallery.
Test Scenario: 1. make a report 2. allow the system to have the permission of the photo gallery 3. upload one to two photos, complete report 4. check the report to see if the photo is uploaded correctly 4. make another report 5. allow the system to have the permission of the camera 6. take a photo and upload it 7. complete report 8. check the report to see if the photo is uploaded correctly.

**Comment by cliu54** [comment]
REQ-1 System: 
Rationale: We want to test the consistency of the system within the same device type. 
Test Scenario: 1. User logs in to the account. 2. User opens up all the features and possible windows. 3. User logs in with another device of the same type. 4. Compares if the system features are the same as the previous ones.

REQ-2 Data: 
Rationale: We want to make sure that the data and report document has a united formatted conversion. This means the data and document are not easily got lost when we used the data type that has already tested stable.

Test Scenario: 1. The user shares different types of repost(achievement records, observation and images) to a third-party platform and sees if they are visible and accessible. 2 Follow the same procedure from the previous step and repost to another third-party platform. Check whether the images and documents are the same as the previous one.
